{% set name = "ipygraphql" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb4b4e17e061afd9b68c87c688a3ce6203ecc18241ae3726a5c130dc660051e0

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipygraphql

about:
  home: http://github.com/mariobuikhuizen/ipygraphql
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Graphql widgets for Jupyter'

  description: |
    Graphql widgets for Jupyter

extra:
  recipe-maintainers:
    - mariobuikhuizen
